language: python
python:
  - "2.7"
  
install:
  - pip install pip==8.1.2
  - pip install --upgrade -r requirements.txt
  - python setup.py develop

script:
  - pyxbgen --binding-root=./ebu_tt_live/bindings -m __init__ --schema-root=./ebu_tt_live/xsd1.1/ -r -u ebutt_live.xsd
  - python setup.py test